export const HS_CODE_STATE = {
		// userId: ,
		// companyId: ,
		code: ``,
		description: ``,
		unit: ``,
		iclslsi: ``,
		preferentialAP: ``,
		preferentialAD: ``,
		preferentialBN: ``,
		preferentialGT: ``,
		preferentialIN: ``,
		preferentialPK: ``,
		preferentialSA: ``,
		preferentialSF: ``,
		preferentialSD: ``,
		preferentialSG: ``,
		genDuty:``,
		vat: ``,
		palGen: ``,
		palsg: ``,
		cessGen:``,
		cessSG: ``,
		surchargeOnCustomsDuty: ``,
		excise: ``,
		sscl: ``,
		scl: ``
};
