export const SHIPMENT_DUTY_STATE = {
	companyId: 0,
	userId: 0,
	shipmentId: 0,
	hsCode: '',
	submittedDateToFinance: '',
	paymentDate: '',
	paymentReference: '',
	remark: '',
	cid: '',
	vat: '',
	pal: '',
	xid: '',
	eic: '',
	ssl: '',
	scl: '',
	penalty: '',
	surcharge: '',
	additionalCharge: '',
};
