export const PURCHASE_ORDER_BANK_STATE = {
	poNo: '',
	paymentMethod: '',
	purchaseAmount: '',
	eta: null,
	DA: {
		bank: null,
		endorsedAmount: null,
		submittedToBank: null,
		endorsementReceivedDate: null,
		bankEndorsementReference: '',
		balanceAmount: null,
		originalDocReceivedDate: null,
		originalDocReceivedReference: '',
		// dueDate: null,
		copyDocsSubmittedToFinance: null,
		remark: '',
	},
	DP: {
		bank: null,
		endorsedAmount: null,
		submittedToBank: null,
		endorsementReceivedDate: null,
		bankEndorsementReference: '',
		balanceAmount: null,
		originalDocReceivedDate: null,
		originalDocReceivedReference: '',
		// dueDate: null,
		copyDocsSubmittedToFinance: null,
		remark: '',
	},
	LC: {
		bank: null,
		latestDateOfShipment: null,
		lcExpiryDate: null,
		lcAmount: null,
		firstDraft: null,
		secondDraft: null,
		thirdDraft: null,
		finalLCReceivedDate: null,
		lcReference: '',
		balanceAmount: null,
		balancePaymentMethod: '',
		requestFromBank: null,
		balancePaidDate: null,
		originalDocReceivedReference: '',
		remark: '',
	},
	OA: {
		bank: null,
		bankReference: '',
		paymentDate: null,
		dueDate: null,
		copyDocsSubmittedToFinance: null,
		remark: '',
	},
	TT: {
		bank: null,
		bankReference: '',
		receivedToSD: null,
		ttRequested: null,
		advanceAmount: '',
		advancePaidDate: null,
		balanceAmount: '',
		balancePaidDate: null,
		remark: '',
	},
};
