export const SHIPMENT_LOGISTICS_INVOICE_STATE = {
	shipmentId: '',
	category: '',
	type: '',
	currency: '',
	amount: '',
	beneficiary: '',
	paymentDueDate: '',
	paymentDate: '',
	paymentReference: '',
	paymentSubmittedDate: '',
	containerNo: '',
	invoiceReceivedDate: '',
	invoiceDate: '',
	remark: '',
};
