// export const SHIPMENT_STATE = {
// 	poId: '',
// 	referenceNo: '',
// 	purchaseOrders: [],
// 	description: '',
// 	vendor: '',
// 	natureOfPurchase: '',
// 	clearingAgent: '',
// 	currency: '',
// 	commercialInvoiceAmount: '',
// 	weight: '',
// 	vessel: '',
// 	incoTerm: '',
// 	eta: '',
// 	docReceivedDateToSD: '',
// 	etd: '',
// 	documentsToCHA: '',
// 	mawb: '',
// 	portOfLoad: '',
// 	shippingLine: '',
// 	shipmentType: '',
// 	commercialInvoiceNo: '',
// 	blawbNo: '',
// 	blawbStatus: '',
// 	demurrage: false,
// 	cargoClearedDate: null,
// 	remarks: '',
// 	cusdecNo: '',
// 	cusdecDate: null,
// 	portOfDischarge: '',
// 	containerDeposit: false,
// 	demurrageAmount: '',
// 	demurrageReason: '',
// 	claimableAmount: '',
// 	claimedAmount: '',
// 	containerNumbers: [],
// 	depositedAmount: '',
// 	acknowledgeDateToFinance: '',
// 	chequeReceivedDate: '',
// 	chequeDepositedDate: '',
// 	chequeNo: '',
// 	deductedAmount: '',
// 	refundedAmount: '',
// 	cdRemarks: '',
// 	typeOfCargo: '',
// 	purchaseAmount: '',
// 	acknowledgeInvoiceReceivedDate: '',
// };

export const SHIPMENT_STATE = {
	poId: '',
	referenceNo: '',
	purchaseOrders: [],
	description: '',
	vendor: '',
	natureOfPurchase: '',
	incoTerm: '',
	shipmentType: '',
	purchaseAmount: '',
	totalAmount: '',
	commercialInvoiceAmount: '',
	typeOfCargo: '',
	clearingAgent: null,
	currency: null,
	weight: null,
	vessel: null,
	eta: null,
	docReceivedDateToSD: null,
	etd: null,
	documentsToCHA: null,
	mawb: null,
	portOfLoad: null,
	shippingLine: null,
	commercialInvoiceNo: null,
	blawbNo: null,
	blawbStatus: null,
	demurrage: false,
	cargoClearedDate: null,
	remarks: null,
	cusdecNo: null,
	cusdecDate: null,
	portOfDischarge: null,
	containerDeposit: false,
	demurrageAmount: null,
	demurrageReason: null,
	claimableAmount: null,
	claimedAmount: null,
	containerNumbers: [],
	depositedAmount: null,
	acknowledgeDateToFinance: null,
	chequeReceivedDate: null,
	chequeDepositedDate: null,
	chequeNo: null,
	deductedAmount: null,
	refundedAmount: null,
	cdRemarks: null,
	acknowledgeInvoiceReceivedDate: null,
	portDemurrageAmount: null,
	reasonForPortDemurrage: null,
	linearDemurrageAmount: null,
	reasonForLinearDemurrage: null,
	transportDetentionAmount: null,
	reasonForTransportDetention: null,
	demurrageRemarks: null,
};
